development:
  adapter: postgresql
  encoding: unicode
  database: writup_app_development
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  database: writeup_app_development
  pool: 5
  host: localhost
  username: action
  password:

