development:
  adapter: postgresql
  encoding: unicode
  database: writeup_app_development
  pool: 5
  host: localhost
  port: 5433
  username: john
  password: password

test:
  adapter: postgresql
  database: writeup_app_test
  encoding: unicode
  pool: 5
  host: localhost
  port: 5433
  username: john
  password: password

production:
  adapter: postgresql
  database: writeup_app_produciton
  encoding: unicode
  pool: 5
  host: localhost
  port: 5433
  username: john
  password: password
